### ISSUE TITLE
Readln and Writeln

### ISSUE THREAD

**Issue by Aspect26** [Aspect26/TrufflePascal#53]
Readln and Writeln buitin subroutines are a TP extension. They are not supported by wirth's standard

**Comment by vhotspur** [comment]
> Readln and Writeln buitin subroutines are a TP extension.

Actually, it is a bit more complicated. [Wirth1973](http://pascal-central.com/docs/pascal1973.pdf) does not mention `readln` and `writeln` (but note the `eol` constant) but they are in [ISO7185, sec. 6.9.2](http://pascal-central.com/iso7185.html#6.9.2%20The%20procedure%20readln).

Does it make sense to support three standards? Or how about making the current `-std=wirth` into ISO?

**Comment by Aspect26** [comment]
the std=wirth is actually the iso standard (my bad with the naming, will be changed in later version)
the readln/writeln thing in the iso is itneresting, because these subroutines are not mentioned in the required subroutiens section [here](http://pascal-central.com/iso7185.html#6.6.6 Required functions) and the write/read functions are.

So shall I implement them for the ISO standard also?

**Comment by vhotspur** [comment]
> the readln/writeln thing in the iso is itneresting, because these subroutines are not mentioned in the required subroutiens section

See note 1 in [6.6.5.2 File handling procedures](http://pascal-central.com/iso7185.html#6.6.5.2%20File%20handling%20procedures). So IMHO they are really part of the standard.
