### ISSUE TITLE
Reading from range type

### ISSUE THREAD

**Issue by Aspect26** [Aspect26/TrufflePascal#85]
Trying to read from a range type results in an exception

var a: 3..10;

begin
 a:=8;
 write(a);  { here }
end.

do we even want this? TP supports it. The behaviour seems to be identical to variable a being integer
EDIT: it doesn't act as an integer, my bad

- [x] reading
- [ ] range checking

**Comment by vhotspur** [comment]
Can you elaborate a bit more what is wrong? The example seems correct to me.

**Comment by Aspect26** [comment]
well, TP supports assignment to a variable of range type. In this concrete example, it allows assigning constant values 3,4,5,6,7,8,9,10 to variable 'a'.
The funny part here is, that it checks the value I'm trying to assign to it only at compile time, so:

```
var a: 3..10;
begin
a:=12;
write(a);
end.
```

won't even compile, but it doesn't test the assignment at runtime, meaning that this:

```
var a: 3..10; v:integer;
begin
v:=12;
a:=v;
write(a);
end.
```

will compile and won't throw any runtime error during execution. 
NOTE: the resulting output will be:
12

**Comment by vhotspur** [comment]
Okay. It seems that [by default](https://community.embarcadero.com/blogs/entry/turbo-pascal-version-10--compiler-directives-39118) the [range checking directive](http://www.math.uni-leipzig.de/pool/tuts/FreePascal/prog/node3.html#SECTION003139000000000000000) is off.

How about silently accepting in TP mode and generating run-time error in ISO mode?

By the way, what changes would be needed to support the `{$X+}`-style directives?

**Comment by Aspect26** [comment]
> By the way, what changes would be needed to support the {$X+}-style directives?
I'd say that specification of grammar would be bit difficult because {} is a comment. Comments in coco/r are specified specially:

`COMMENTS FROM "{" TO "}"`
 
and I don't think it is possible to get what is inside of them.
