### ISSUE TITLE
put and get functions

### ISSUE THREAD

**Issue by Aspect26** [Aspect26/TrufflePascal#87]
put(f) and get(f) are requierd functions shich will NOT be supported. 
There shall be at least a detection of this subroutines which will result in some nice runtime exception (at the time of their call).

dev-note: create a builtin node just like for other function whose specialization will only throw the exception.
EDIT: Compile time exception

**Comment by vhotspur** [comment]
I would rather see a compile-time exception to warn the user in advance that the program will not work.
